import type { Metadata } from 'next';
import './globals.css';
import AuthProvider from '@/supabase/auth/provider';
import { Suspense } from 'react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Suspense fallback={'loading...'}>
					<AuthProvider>{children}</AuthProvider>
				</Suspense>
			</body>
		</html>
	);
}
